apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y3jmer7e4-nodejs
  janus-idp.io/tekton: y3jmer7e4-nodejs
  backstage.io/kubernetes-id: y3jmer7e4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y3jmer7e4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
